### PR TITLE
Update pt_PT translation

### PR DESCRIPTION
**Pull request by JSFernandes**
This PR translates some new sections of the pt_PT translation and tweaks some existing translations. This translation does not follow the new orthographic agreement and and the pt_BR translation was consulted for some terminology.

This was already tested for text size in the application and will be ok to merge after some feedback.

### CODE REVIEW

**Comment by vnctdj** [comment]
I see no problem for merging, just tell us when you think it's ready :)

**Comment by cyb3rm4n** [comment]
I think he needs feedback from portugal people.

**Comment by tiagoc** [comment]
:thumbsup:
Good job, seems ready for merging.

**Comment by cyb3rm4n** [comment]
done)

**Pull request merged**
