### PR TITLE
Update en_US.ini

### PR DESCRIPTION
**Pull request by zminhquanz**
update The 3rd Birthday for Force depth write , so newbie can config this game for easily

### CODE REVIEW

**Comment by vnctdj** [comment]
Are you sure this setting is only useful for *The 3rd Birthday* ?
Your other pull request (https://github.com/hrydgard/ppsspp-lang/pull/467/files#diff-8d23dd2bb3a0ada0aed2e8be38a5cb89R282) is also concerned by this question.

**Comment by zminhquanz** [comment]
yes sir

**Comment by zminhquanz** [comment]
but not only The 3rd Birthday affect,  and a few game is affect that

**Comment by vnctdj** [comment]
Hum, OK then :)
One thing though, could you please remove the spaces after "(" and before ")" ? Don't forget to do that in your other pull request too :)

**Comment by vnctdj** [comment]
Why did you closed it ?
You just have to push another commit to do the edit :)

**Comment by zminhquanz** [comment]
because force depth write is affect a few game , not only The 3rd Birthday , so I'm close it and do another commit

**Pull request closed without merging**
