### PR TITLE
Update ru_RU.ini

### PR DESCRIPTION
**Pull request by ghost**
screenshot_2015-01-29-15-41-37
Small corrections.

### CODE REVIEW

**Comment by QWEmct** [comment]
For a pause, it doesn′t work?

screenshot_2015-01-29-15-43-18

**Comment by sum2012** [comment]
Anyway,do you want us merge this commit first ?

**Comment by QWEmct** [comment]
@sum2012 
"Anyway,do you want us merge this commit first ?"
Yes

**Comment by sum2012** [comment]
https://github.com/hrydgard/ppsspp/commit/626e2fc2c8d857c50a7d47974f6baf1fd561d90c fix it
so I merge this commit

**Pull request merged**
