### PR TITLE
Example for issue #666

### PR DESCRIPTION
**Pull request by Florin9doi**

### CODE REVIEW

**Comment by hrydgard** [comment]
So do you want to merge this or what?

**Comment by Florin9doi** [comment]
This patch is good but other patch(es) are needed to complete #666

**Comment by hrydgard** [comment]
Alright, I'll let it stick around for a bit and then merge it then unless another change supersedes it.

**Comment by Florin9doi** [comment]
replaced by https://github.com/hrydgard/ppsspp-lang/pull/693

**Pull request closed without merging**
