### PR TITLE
Update arabic

### PR DESCRIPTION
**Pull request by Omaranwa**
Donot merge yet

### CODE REVIEW

**Comment by hrydgard** [comment]
Just say when it's OK to merge :)

**Comment by Omaranwa** [comment]
ok i will do

**Comment by vnctdj** [comment]
I resolved the conflict :)
GitHub doesn't seem to update and still shows "This branch has conflicts that must be resolved" though...

**Comment by vnctdj** [comment]
@Omaranwa 
If it wasn't clear, there is no problem merging your pull request.
Just tell us when it's OK for you :)

**Comment by Omaranwa** [comment]
ok its about 80% done 
you can mirage it

**Pull request merged**
