### PR TITLE
Update ru_RU.ini

### PR DESCRIPTION
**Pull request by SukharevAndrey**
Fix ugly translation by Drui7. He didn't even check his translation in application.

### CODE REVIEW

**Comment by Drui7** [comment]
I was very annoyed like you, those who are foaming at the mouth screaming that his opinion is the highest authority. and now I tell you @SukharevAndrey why you're wrong not to hold war edits.
1) what I did - this translation, with a human, not a machine, my opinion. and if you're going to name my opinion, "ugly", it is a stone in your hand, but not in my.
2) you made a stylistic changes. sometimes it's more appropriate than mine, sometimes it's an analogy. so be it, I will not fix it.
3) but the word "Расшарить", it should not be in the TRANSLATION.
in the Russian language, a lot of words, you could find another, if you do not like my "Поделиться" (which translates as even Google to "share").
but you get the English word "share", succeeded him in the letters on the Russian added verb suffix and called this transfer. came the word: Рас + share + ить. it is not a translation, it's stupid transcription!
result:
you spent some stylistic changes strings to their opinion, instead of literary words added jargon-transcription, and then my opinion has called "ugly."
oh, how I have burns from such *******

I do not like to "Поделиться" - think synonymous, but not to do stupid transliteration as in games early 90s.

**Comment by hrydgard** [comment]
Sorry, I shouldn't have merged this with that description. I didn't even read it.

Unfortunately, I don't speak Russian so it's hard for me to see what is right. @Drui7 , if you send a pull request I'll definitely consider merging it, your arguments are good.

**Comment by SukharevAndrey** [comment]
@Drui7 I'm sorry for word "ugly", but your translation of "Sharing" is even worse. "Деление" means "division". Word "расшаривание" is indeed a non dictionary word, but it's in use and almost everyone knows it's meaning.
@hrydgard He's a bit overreacting, and me too. But his translation is not better.

**Comment by Drui7** [comment]
@SukharevAndrey I'm not saying that my translation is better, I moved to whip up something that was in English. Some of your changes have liked me, so let's leave, but the word "rassharivat" horrible. because they do not like my version, ask your, let there be any Russian word with a similar meaning, but not the transliteration.
higher than what I had already written.

**Comment by Drui7** [comment]
I suggest:
RemoteISOScanning -- ... "Поделиться играми" ...
Stop Sharing -- Передача данных остановлена
Share Games -- Поделиться играми (передача данных)

**Pull request merged**
