### PR TITLE
Fixes #666

### LINKED ISSUE #666: PC and Android versions don't match (Farsi/Arabic)
I know this isn't really PPSSPP's fault, but the Android version translations are messed up. It looks fine on PC:
**PC**:
image

**Android**:
screenshot_2018-05-16-22-02-06-614_org ppsspp ppsspp

I think it's because Android doesn't have a proper RTL implementation.

I was hoping you could provide some tips for fixing it.

### PR DESCRIPTION
**Pull request by Florin9doi**
Needs to be tested

### CODE REVIEW

**Comment by leopard20** [comment]
Is it just me or are those files exactly the sams as before?!

**Comment by Florin9doi** [comment]
This patch inserts one hidden character (U+200E) before every string which contains arabic text.
The changes were made automatically with the following command:
```
# perl -CSAD -p -i -e 's/(.* = )(?!\x{200e})(.*\p{Arabic}.*)/\1\x{200e}\2/g' ar_AE.ini
``` 
The command is also saved in this patch, at the top of `ar_AE.ini` file for future usage.

You cannot see the character , but it is present:
untitled

**Comment by hrydgard** [comment]
Sorry, forgot to merge this.

**Comment by leopard20** [comment]
@hrydgard Could you please update the lang directory in the ppsspp repo again so I can test this?

**Comment by hrydgard** [comment]
@leopard20 Done!

**Comment by leopard20** [comment]
Thanks. It works great!

**Pull request merged**
