### PR TITLE
Update th_TH.ini V.3

### PR DESCRIPTION
**Pull request by Saramagrean**
Fix crash on Android when press button settings mainscreen (Thai language only) & Update some translation [Completed!]
Thank you Henrik-sama Have a nice day!! :-)

### CODE REVIEW

**Comment by hrydgard** [comment]
Hm, crash? What made it crash?

**Comment by Saramagrean** [comment]
Not sure sir. I'm delete all line and redo it again
//Sorry for my bad english... T T

**Comment by sum2012** [comment]
@Saramagrean You need add more translation 
see 
https://github.com/hrydgard/ppsspp-lang/commit/6e5ed5b281e3e0b3d8a7658d160c6787f6c99716
and
https://github.com/hrydgard/ppsspp-lang/commit/1ece83a0e4336fa2ba9e1b6123cc6594339d4812

**Comment by Saramagrean** [comment]
Roger 😀

**Pull request merged**
