### PR TITLE
All languages updated from en_US

### PR DESCRIPTION
**Pull request by vnctdj**
If you don't agree with the changes done to your language file, simply go back to the previous version.

### CODE REVIEW

**Comment by sum2012** [comment]
I quick to view,just find that you deleted my transate.
I will repair myself

**Comment by vnctdj** [comment]
Oh, I understand why, it's because there was 2 spaces before the "=" sign on that line...
I didn't see this, sorry :/

**Comment by sum2012** [comment]
I see.In the other hand,thanks for deleted unused transated(and I know what transate missing)

**Comment by vnctdj** [comment]
Glad to see my work is useful to you :)

**Pull request merged**
