### PR TITLE
Updated translation

### PR DESCRIPTION
**Pull request by Felipefpl**
I saw there were changes in the translations' files so i updated the brazilian translation too.

Why another site for translations instead of using the emu's github site like most ppl do?

### CODE REVIEW

**Comment by hrydgard** [comment]
For a while we had too many translation commits, it would have gotten too messy. That was a long time ago though, and you're right, it's probably time to merge back into the main repo.

**Comment by hrydgard** [comment]
Something has gone wrong here though - look at the "Files Changed", it looks like all lines are changes which makes it impossible to review. Maybe a line ending issue? I'll see if I can fix it.

**Comment by hrydgard** [comment]
I'm replacing this PR with this: https://github.com/hrydgard/ppsspp-lang/pull/789/files

**Comment by Felipefpl** [comment]
> For a while we had too many translation commits, it would have gotten too messy. That was a long time ago though, and you're right, it's probably time to merge back into the main repo. Made an issue: [hrydgard/ppsspp#14612](https://github.com/hrydgard/ppsspp/issues/14612)

I see, thanks for the info.

> Something has gone wrong here though - look at the "Files Changed", it looks like all lines are changes which makes it impossible to review. Maybe a line ending issue? I'll see if I can fix it.

Strange indeed, AFAIK i didnt change anything aside adding words, 3 dots at the end of phrases or re-translate a small number of strings in a better way. I hope it's not too serious of a problem.

**Pull request closed without merging**
