### PR TITLE
Update zh_CN.ini

### PR DESCRIPTION
**Pull request by Miigon**
修正一些翻译，添加一些漏译的翻译

### CODE REVIEW

**Comment by vnctdj** [comment]
I don't agree with this pull request, here are some reasons : 
* "#保留第一行，防止Audio不被正确识别" >> I don't see why you would need this line, [Audio] is working well.
* You are adding some old translations that no longer exist, please use the latest build.
* Please don't delete empty lines, they help keeping the file more clear.

Also, on a side note, I know that *en_US* is not updated as the moment, but I will update it soon, as [I said earlier](https://github.com/hrydgard/ppsspp-lang/commit/268952cc8045eabdeda21bd1c470cf93924f7d84#commitcomment-15519810).

**Comment by unknownbrackets** [comment]
Hmm, maybe there's an encoding mark in the first line, and that's what you're trying to avoid with the comment?  Try a file editor and save the file as utf-8.

-[Unknown]

**Comment by sum2012** [comment]
@Miigon I have used your translate in
https://github.com/hrydgard/ppsspp-lang/commit/2ae5b65dafdaa2b8592ab4c23ace1b8c2bcdcf89

**Comment by vnctdj** [comment]
Thanks @sum2012, let's close this pull request then :)

**Pull request closed without merging**
