### PR TITLE
Update id_ID.ini

### PR DESCRIPTION
**Pull request by ubunteroz**

### CODE REVIEW

**Comment by hrydgard** [comment]
This seems to mostly remove the id and replace with en language. Is that really the intention?

**Comment by ubunteroz** [comment]
Umm no, my intention is to rework this translation from beginning. Current translation is so messed up and hard to maintain. So this PR is still work in progress, sorry for not updating this PR for about two weeks.

**Comment by ubunteroz** [comment]
I think it's enough for now :thinking:

**Comment by hrydgard** [comment]
Alright!

**Pull request merged**
