### PR TITLE
Updated tg_PH.ini

### PR DESCRIPTION
**Pull request by StoneArtz**
I'm so very sorry about the error because I've edit it on my phone for now

### CODE REVIEW

**Comment by StoneArtz** [comment]
Can I help translating tagalog language?

**Comment by StoneArtz** [comment]
BTW, ignore the "Update tg_PH.ini"

**Comment by hrydgard** [comment]
Ignore, why? Is this pull request ready as-is? If so, I'll happily merge.

**Comment by StoneArtz** [comment]
Im so sorry, its ready!

**Comment by StoneArtz** [comment]
I'm going to update it again. I'm so very sorry.

**Pull request closed without merging**
