### PR TITLE
Update zh_TW.ini

### PR DESCRIPTION
**Pull request by hiunnhue**

### CODE REVIEW

**Comment by sum2012** [comment]
I don't agree
Buffered Rendering = 緩衝繪圖
Other okay

**Comment by hiunnhue** [comment]
How about 緩衝繪製 or 緩衝彩現 ?

**Comment by sum2012** [comment]
Hmm,still not good enough

**Comment by hiunnhue** [comment]
Do you have any suggestion? I cannot come up with a better solution ... or maybe I just leave it unchanged?

**Comment by sum2012** [comment]
Yes,leave it unchanged (緩衝渲染)

**Comment by hiunnhue** [comment]
OK, I've changed them back.

**Pull request merged**
